- name: Testing Ansible
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get uptime
      shell: /usr/bin/uptime
      register: result

    - name: prints the uptime of the system
      debug:
        var: result